# Copyright (C) 2014-2016 The CyanogenMod Project
# Copyright (C) 2017 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/fih/lso/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/fih/lso/proprietary/bin/bdaddr_loader:system/bin/bdaddr_loader \
    vendor/fih/lso/proprietary/bin/btnvtool:system/bin/btnvtool \
    vendor/fih/lso/proprietary/bin/hci_qcomm_init:system/bin/hci_qcomm_init \
    vendor/fih/lso/proprietary/bin/mm-qcamera-daemon:system/bin/mm-qcamera-daemon \
    vendor/fih/lso/proprietary/bin/sensors.qcom:system/bin/sensors.qcom \
    vendor/fih/lso/proprietary/etc/acdbdata/Bluetooth_cal.acdb:system/etc/acdbdata/Bluetooth_cal.acdb \
    vendor/fih/lso/proprietary/etc/acdbdata/General_cal.acdb:system/etc/acdbdata/General_cal.acdb \
    vendor/fih/lso/proprietary/etc/acdbdata/Global_cal.acdb:system/etc/acdbdata/Global_cal.acdb \
    vendor/fih/lso/proprietary/etc/acdbdata/Handset_cal.acdb:system/etc/acdbdata/Handset_cal.acdb \
    vendor/fih/lso/proprietary/etc/acdbdata/Hdmi_cal.acdb:system/etc/acdbdata/Hdmi_cal.acdb \
    vendor/fih/lso/proprietary/etc/acdbdata/Headset_cal.acdb:system/etc/acdbdata/Headset_cal.acdb \
    vendor/fih/lso/proprietary/etc/acdbdata/Speaker_cal.acdb:system/etc/acdbdata/Speaker_cal.acdb \
    vendor/fih/lso/proprietary/etc/firmware/Signedrompatch_v20.bin:system/etc/firmware/Signedrompatch_v20.bin \
    vendor/fih/lso/proprietary/etc/firmware/Signedrompatch_v21.bin:system/etc/firmware/Signedrompatch_v21.bin \
    vendor/fih/lso/proprietary/etc/firmware/Signedrompatch_v24.bin:system/etc/firmware/Signedrompatch_v24.bin \
    vendor/fih/lso/proprietary/etc/firmware/Signedrompatch_v30.bin:system/etc/firmware/Signedrompatch_v30.bin \
    vendor/fih/lso/proprietary/etc/firmware/a225_pfp.fw:system/etc/firmware/a225_pfp.fw \
    vendor/fih/lso/proprietary/etc/firmware/a225_pm4.fw:system/etc/firmware/a225_pm4.fw \
    vendor/fih/lso/proprietary/etc/firmware/a225p5_pm4.fw:system/etc/firmware/a225p5_pm4.fw \
    vendor/fih/lso/proprietary/etc/firmware/a300_pfp.fw:system/etc/firmware/a300_pfp.fw \
    vendor/fih/lso/proprietary/etc/firmware/a300_pm4.fw:system/etc/firmware/a300_pm4.fw \
    vendor/fih/lso/proprietary/etc/firmware/a330_pfp.fw:system/etc/firmware/a330_pfp.fw \
    vendor/fih/lso/proprietary/etc/firmware/a330_pm4.fw:system/etc/firmware/a330_pm4.fw \
    vendor/fih/lso/proprietary/etc/firmware/cpp_firmware_v1_1_1.fw:system/etc/firmware/cpp_firmware_v1_1_1.fw \
    vendor/fih/lso/proprietary/etc/firmware/cpp_firmware_v1_1_6.fw:system/etc/firmware/cpp_firmware_v1_1_6.fw \
    vendor/fih/lso/proprietary/etc/firmware/cpp_firmware_v1_2_0.fw:system/etc/firmware/cpp_firmware_v1_2_0.fw \
    vendor/fih/lso/proprietary/etc/firmware/cpp_firmware_v1_2_1.fw:system/etc/firmware/cpp_firmware_v1_2_1.fw \
    vendor/fih/lso/proprietary/etc/firmware/fw_bcmdhd.bin:system/etc/firmware/fw_bcmdhd.bin \
    vendor/fih/lso/proprietary/etc/firmware/fw_bcmdhd_apsta.bin:system/etc/firmware/fw_bcmdhd_apsta.bin \
    vendor/fih/lso/proprietary/etc/firmware/fw_bcmdhd_mfg.bin:system/etc/firmware/fw_bcmdhd_mfg.bin \
    vendor/fih/lso/proprietary/etc/firmware/leia_pfp_470.fw:system/etc/firmware/leia_pfp_470.fw \
    vendor/fih/lso/proprietary/etc/firmware/leia_pm4_470.fw:system/etc/firmware/leia_pm4_470.fw \
    vendor/fih/lso/proprietary/etc/firmware/nfc_test.bin:system/etc/firmware/nfc_test.bin \
    vendor/fih/lso/proprietary/etc/firmware/venus.b00:system/etc/firmware/venus.b00 \
    vendor/fih/lso/proprietary/etc/firmware/venus.b01:system/etc/firmware/venus.b01 \
    vendor/fih/lso/proprietary/etc/firmware/venus.b02:system/etc/firmware/venus.b02 \
    vendor/fih/lso/proprietary/etc/firmware/venus.b03:system/etc/firmware/venus.b03 \
    vendor/fih/lso/proprietary/etc/firmware/venus.b04:system/etc/firmware/venus.b04 \
    vendor/fih/lso/proprietary/etc/firmware/venus.mbn:system/etc/firmware/venus.mbn \
    vendor/fih/lso/proprietary/etc/firmware/venus.mdt:system/etc/firmware/venus.mdt \
    vendor/fih/lso/proprietary/lib/hw/camera.vendor.msm8226.so:system/lib/hw/camera.vendor.msm8226.so \
    vendor/fih/lso/proprietary/lib/libatd_corelib.so:system/lib/libatd_corelib.so \
    vendor/fih/lso/proprietary/lib/liblgftmitem.so:system/lib/liblgftmitem.so \
    vendor/fih/lso/proprietary/lib/libqomx_core.so:system/lib/libqomx_core.so \
    vendor/fih/lso/proprietary/system/etc/firmware/keymaster.b00:system/system/etc/firmware/keymaster.b00 \
    vendor/fih/lso/proprietary/system/etc/firmware/keymaster.b01:system/system/etc/firmware/keymaster.b01 \
    vendor/fih/lso/proprietary/system/etc/firmware/keymaster.b02:system/system/etc/firmware/keymaster.b02 \
    vendor/fih/lso/proprietary/system/etc/firmware/keymaster.b03:system/system/etc/firmware/keymaster.b03 \
    vendor/fih/lso/proprietary/system/etc/firmware/keymaster.mdt:system/system/etc/firmware/keymaster.mdt \
    vendor/fih/lso/proprietary/system/lib/libHDR.so:system/system/lib/libHDR.so \
    vendor/fih/lso/proprietary/system/lib/libchromatix_imx219_default_video.so:system/system/lib/libchromatix_imx219_default_video.so \
    vendor/fih/lso/proprietary/system/lib/libmm-omxcore.so:system/system/lib/libmm-omxcore.so \
    vendor/fih/lso/proprietary/system/lib/libmm-qcamera.so:system/system/lib/libmm-qcamera.so \
    vendor/fih/lso/proprietary/system/lib/libmmcamera_interface.so:system/system/lib/libmmcamera_interface.so \
    vendor/fih/lso/proprietary/system/lib/libmmjpeg_interface.so:system/system/lib/libmmjpeg_interface.so \
    vendor/fih/lso/proprietary/system/lib/libmorpho_image_stab31.so:system/system/lib/libmorpho_image_stab31.so \
    vendor/fih/lso/proprietary/system/lib/libmorpho_noise_reduction.so:system/system/lib/libmorpho_noise_reduction.so \
    vendor/fih/lso/proprietary/system/lib/libqomx_core.so:system/system/lib/libqomx_core.so \
    vendor/fih/lso/proprietary/system/vendor/lib/lib-imscamera.so:system/system/vendor/lib/lib-imscamera.so \
    vendor/fih/lso/proprietary/system/vendor/lib/libI420colorconvert.so:system/system/vendor/lib/libI420colorconvert.so \
    vendor/fih/lso/proprietary/system/vendor/lib/libWVStreamControlAPI_L3.so:system/system/vendor/lib/libWVStreamControlAPI_L3.so \
    vendor/fih/lso/proprietary/system/vendor/lib/libchromatix_imx132_common.so:system/system/vendor/lib/libchromatix_imx132_common.so \
    vendor/fih/lso/proprietary/system/vendor/lib/libchromatix_imx132_default_video.so:system/system/vendor/lib/libchromatix_imx132_default_video.so \
    vendor/fih/lso/proprietary/system/vendor/lib/libchromatix_imx132_liveshot.so:system/system/vendor/lib/libchromatix_imx132_liveshot.so \
    vendor/fih/lso/proprietary/system/vendor/lib/libchromatix_imx132_preview.so:system/system/vendor/lib/libchromatix_imx132_preview.so \
    vendor/fih/lso/proprietary/system/vendor/lib/libchromatix_imx132_skt_common.so:system/system/vendor/lib/libchromatix_imx132_skt_common.so \
    vendor/fih/lso/proprietary/system/vendor/lib/libchromatix_imx132_skt_preview.so:system/system/vendor/lib/libchromatix_imx132_skt_preview.so \
    vendor/fih/lso/proprietary/system/vendor/lib/libchromatix_imx132_skt_video.so:system/system/vendor/lib/libchromatix_imx132_skt_video.so \
    vendor/fih/lso/proprietary/system/vendor/lib/libchromatix_imx132_snapshot.so:system/system/vendor/lib/libchromatix_imx132_snapshot.so \
    vendor/fih/lso/proprietary/system/vendor/lib/libchromatix_imx219_common.so:system/system/vendor/lib/libchromatix_imx219_common.so \
    vendor/fih/lso/proprietary/system/vendor/lib/libchromatix_imx219_imtech_common.so:system/system/vendor/lib/libchromatix_imx219_imtech_common.so \
    vendor/fih/lso/proprietary/system/vendor/lib/libchromatix_imx219_imtech_default_video.so:system/system/vendor/lib/libchromatix_imx219_imtech_default_video.so \
    vendor/fih/lso/proprietary/system/vendor/lib/libchromatix_imx219_imtech_preview.so:system/system/vendor/lib/libchromatix_imx219_imtech_preview.so \
    vendor/fih/lso/proprietary/system/vendor/lib/libchromatix_imx219_imtech_skt_default_video.so:system/system/vendor/lib/libchromatix_imx219_imtech_skt_default_video.so \
    vendor/fih/lso/proprietary/system/vendor/lib/libchromatix_imx219_imtech_snapshot.so:system/system/vendor/lib/libchromatix_imx219_imtech_snapshot.so \
    vendor/fih/lso/proprietary/system/vendor/lib/libchromatix_imx219_mms_video.so:system/system/vendor/lib/libchromatix_imx219_mms_video.so \
    vendor/fih/lso/proprietary/system/vendor/lib/libchromatix_imx219_preview.so:system/system/vendor/lib/libchromatix_imx219_preview.so \
    vendor/fih/lso/proprietary/system/vendor/lib/libchromatix_imx219_skt_default_video.so:system/system/vendor/lib/libchromatix_imx219_skt_default_video.so \
    vendor/fih/lso/proprietary/system/vendor/lib/libchromatix_imx219_snapshot.so:system/system/vendor/lib/libchromatix_imx219_snapshot.so \
    vendor/fih/lso/proprietary/system/vendor/lib/libjpegdhw.so:system/system/vendor/lib/libjpegdhw.so \
    vendor/fih/lso/proprietary/system/vendor/lib/libjpegehw.so:system/system/vendor/lib/libjpegehw.so \
    vendor/fih/lso/proprietary/system/vendor/lib/libmm-hdcpmgr.so:system/system/vendor/lib/libmm-hdcpmgr.so \
    vendor/fih/lso/proprietary/system/vendor/lib/libmmcamera2_c2d_module.so:system/system/vendor/lib/libmmcamera2_c2d_module.so \
    vendor/fih/lso/proprietary/system/vendor/lib/libmmcamera2_cpp_module.so:system/system/vendor/lib/libmmcamera2_cpp_module.so \
    vendor/fih/lso/proprietary/system/vendor/lib/libmmcamera2_frame_algorithm.so:system/system/vendor/lib/libmmcamera2_frame_algorithm.so \
    vendor/fih/lso/proprietary/system/vendor/lib/libmmcamera2_iface_modules.so:system/system/vendor/lib/libmmcamera2_iface_modules.so \
    vendor/fih/lso/proprietary/system/vendor/lib/libmmcamera2_imglib_modules.so:system/system/vendor/lib/libmmcamera2_imglib_modules.so \
    vendor/fih/lso/proprietary/system/vendor/lib/libmmcamera2_is.so:system/system/vendor/lib/libmmcamera2_is.so \
    vendor/fih/lso/proprietary/system/vendor/lib/libmmcamera2_isp_modules.so:system/system/vendor/lib/libmmcamera2_isp_modules.so \
    vendor/fih/lso/proprietary/system/vendor/lib/libmmcamera2_pproc_modules.so:system/system/vendor/lib/libmmcamera2_pproc_modules.so \
    vendor/fih/lso/proprietary/system/vendor/lib/libmmcamera2_sensor_modules.so:system/system/vendor/lib/libmmcamera2_sensor_modules.so \
    vendor/fih/lso/proprietary/system/vendor/lib/libmmcamera2_stats_algorithm.so:system/system/vendor/lib/libmmcamera2_stats_algorithm.so \
    vendor/fih/lso/proprietary/system/vendor/lib/libmmcamera2_stats_modules.so:system/system/vendor/lib/libmmcamera2_stats_modules.so \
    vendor/fih/lso/proprietary/system/vendor/lib/libmmcamera2_vpe_module.so:system/system/vendor/lib/libmmcamera2_vpe_module.so \
    vendor/fih/lso/proprietary/system/vendor/lib/libmmcamera2_wnr_module.so:system/system/vendor/lib/libmmcamera2_wnr_module.so \
    vendor/fih/lso/proprietary/system/vendor/lib/libmmcamera_faceproc.so:system/system/vendor/lib/libmmcamera_faceproc.so \
    vendor/fih/lso/proprietary/system/vendor/lib/libmmcamera_hdr_gb_lib.so:system/system/vendor/lib/libmmcamera_hdr_gb_lib.so \
    vendor/fih/lso/proprietary/system/vendor/lib/libmmcamera_hdr_lib.so:system/system/vendor/lib/libmmcamera_hdr_lib.so \
    vendor/fih/lso/proprietary/system/vendor/lib/libmmcamera_imglib.so:system/system/vendor/lib/libmmcamera_imglib.so \
    vendor/fih/lso/proprietary/system/vendor/lib/libmmcamera_imx132.so:system/system/vendor/lib/libmmcamera_imx132.so \
    vendor/fih/lso/proprietary/system/vendor/lib/libmmcamera_imx219.so:system/system/vendor/lib/libmmcamera_imx219.so \
    vendor/fih/lso/proprietary/system/vendor/lib/libmmcamera_imx219_eeprom.so:system/system/vendor/lib/libmmcamera_imx219_eeprom.so \
    vendor/fih/lso/proprietary/system/vendor/lib/libmmcamera_tintless_algo.so:system/system/vendor/lib/libmmcamera_tintless_algo.so \
    vendor/fih/lso/proprietary/system/vendor/lib/libmmcamera_tintless_bg_pca_algo.so:system/system/vendor/lib/libmmcamera_tintless_bg_pca_algo.so \
    vendor/fih/lso/proprietary/system/vendor/lib/libmmcamera_tuning.so:system/system/vendor/lib/libmmcamera_tuning.so \
    vendor/fih/lso/proprietary/system/vendor/lib/libmmcamera_wavelet_lib.so:system/system/vendor/lib/libmmcamera_wavelet_lib.so \
    vendor/fih/lso/proprietary/system/vendor/lib/libmmjpeg.so:system/system/vendor/lib/libmmjpeg.so \
    vendor/fih/lso/proprietary/system/vendor/lib/libmmqjpeg_codec.so:system/system/vendor/lib/libmmqjpeg_codec.so \
    vendor/fih/lso/proprietary/system/vendor/lib/libqomx_jpegdec.so:system/system/vendor/lib/libqomx_jpegdec.so \
    vendor/fih/lso/proprietary/system/vendor/lib/libqomx_jpegenc.so:system/system/vendor/lib/libqomx_jpegenc.so \
    vendor/fih/lso/proprietary/system/vendor/lib/libwvm.so:system/system/vendor/lib/libwvm.so \
    vendor/fih/lso/proprietary/vendor/firmware/BCM4334B0_002.001.013.1817.2169.hcd:system/vendor/firmware/BCM4334B0_002.001.013.1817.2169.hcd \
    vendor/fih/lso/proprietary/vendor/firmware/libpn547_fw.so:system/vendor/firmware/libpn547_fw.so \
    vendor/fih/lso/proprietary/vendor/lib/hw/sensors.msm8226.so:system/vendor/lib/hw/sensors.msm8226.so \
    vendor/fih/lso/proprietary/vendor/lib/libacdbloader.so:system/vendor/lib/libacdbloader.so \
    vendor/fih/lso/proprietary/vendor/lib/libalarmservice_jni.so:system/vendor/lib/libalarmservice_jni.so \
    vendor/fih/lso/proprietary/vendor/lib/libsensor1.so:system/vendor/lib/libsensor1.so \
    vendor/fih/lso/proprietary/vendor/lib/libsensor_lge_cal.so:system/vendor/lib/libsensor_lge_cal.so \
    vendor/fih/lso/proprietary/vendor/lib/libsensor_reg.so:system/vendor/lib/libsensor_reg.so \
    vendor/fih/lso/proprietary/vendor/lib/libsensor_test.so:system/vendor/lib/libsensor_test.so \
    vendor/fih/lso/proprietary/vendor/lib/libsensor_thresh.so:system/vendor/lib/libsensor_thresh.so \
    vendor/fih/lso/proprietary/vendor/lib/libsensor_user_cal.so:system/vendor/lib/libsensor_user_cal.so \
    vendor/fih/lso/proprietary/vendor/lib/rfsa/adsp/libadsp_denoise_skel.so:system/vendor/lib/rfsa/adsp/libadsp_denoise_skel.so \
    vendor/fih/lso/proprietary/vendor/lib/rfsa/adsp/libapps_mem_heap.so:system/vendor/lib/rfsa/adsp/libapps_mem_heap.so \
    vendor/fih/lso/proprietary/vendor/lib/rfsa/adsp/libdspCV_skel.so:system/vendor/lib/rfsa/adsp/libdspCV_skel.so \
    vendor/fih/lso/proprietary/vendor/lib/rfsa/adsp/libfastcvadsp.so:system/vendor/lib/rfsa/adsp/libfastcvadsp.so \
    vendor/fih/lso/proprietary/vendor/lib/rfsa/adsp/libfastcvadsp_skel.so:system/vendor/lib/rfsa/adsp/libfastcvadsp_skel.so \
    vendor/fih/lso/proprietary/vendor/lib/rfsa/adsp/libscveT2T_skel.so:system/vendor/lib/rfsa/adsp/libscveT2T_skel.so

PRODUCT_PACKAGES += \
    libbtnv
